# Load with: 
#    conda env create -f environment.yml
# Activate with: 
#    conda activate observadoscraper

name: observadoscraper
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - bs4
  - selenium
  - pytest
  - pip
  - pip:
    - simplekml
    - webdriver_manager