from scripts.migrationtrendfun import GetSpeciesPlot
from datetime import datetime as dt


end_year = dt.now().year-1
start_year = end_year -5


#GetSpeciesPlot(start_year,end_year, 1, 12, 781,   "Zwarte Rotgans")
#GetSpeciesPlot(start_year,end_year, 1, 12, 769,   "Witbuikrotgans")
#GetSpeciesPlot(start_year,end_year, 1, 12, 313,   "Roodhalsgans")
#GetSpeciesPlot(start_year,end_year, 1, 12, 327,   "Sneeuwgans")
#GetSpeciesPlot(start_year,end_year, 1, 12, 338,   "Taigarietgans")
#GetSpeciesPlot(start_year,end_year, 1, 12, 244,   "Dwerggans")
#GetSpeciesPlot(start_year,end_year, 1, 12, 772,   "Witoogeend")
#GetSpeciesPlot(start_year,end_year, 1, 12, 264,   "Ijseend")
#GetSpeciesPlot(start_year,end_year, 1, 12, 216,   "Alpengierzwaluw")
#GetSpeciesPlot(start_year,end_year, 1, 12, 18,    "Kwartelkoning")
#GetSpeciesPlot(start_year,end_year, 1, 12, 17,    "Porseleinhoen")
#GetSpeciesPlot(start_year,end_year, 1, 12, 19,    "Kraanvogel")
#GetSpeciesPlot(start_year,end_year, 1, 12, 1401,  "Flamingo")
#GetSpeciesPlot(start_year,end_year, 1, 12, 332, 	"Steltkluut")
#GetSpeciesPlot(start_year,end_year, 1, 12, 294, 	"Morinelplevier")
GetSpeciesPlot(start_year,end_year, 1, 12, 905, 	"Breedbekstrandloper")
GetSpeciesPlot(start_year,end_year, 1, 12, 370, 	"Gestreepte strandloper")
GetSpeciesPlot(start_year,end_year, 1, 12, 253, 	"Grauwe franjepoot")
GetSpeciesPlot(start_year,end_year, 1, 12, 318, 	"Rosse franjepoot")
GetSpeciesPlot(start_year,end_year, 1, 12, 307, 	"Poelruiter")
GetSpeciesPlot(start_year,end_year, 1, 12, 1387,  "Vorkstaartmeeuw")
GetSpeciesPlot(start_year,end_year, 1, 12, 255,   "Grote burgemeester")
GetSpeciesPlot(start_year,end_year, 1, 12, 272,   "Kleine burgemeester")
GetSpeciesPlot(start_year,end_year, 1, 12, 368,   "Lachstern")
GetSpeciesPlot(start_year,end_year, 1, 12, 762,   "Witwangstern")
GetSpeciesPlot(start_year,end_year, 1, 12, 361,   "Witvleugelstern")
GetSpeciesPlot(start_year,end_year, 1, 12, 278,   "Kleinste Jager")
GetSpeciesPlot(start_year,end_year, 1, 12, 270,   "Kleine alk")
GetSpeciesPlot(start_year,end_year, 1, 12, 1538,  "Zwarte zeekoet")
GetSpeciesPlot(start_year,end_year, 1, 12, 304,   "Papegaaiduiker")
GetSpeciesPlot(start_year,end_year, 1, 12, 263,   "Ijsduiker")
GetSpeciesPlot(start_year,end_year, 1, 12, 335,   "Stormvogeltje")
GetSpeciesPlot(start_year,end_year, 1, 12, 369,   "Vale pijlstormvogel")
GetSpeciesPlot(start_year,end_year, 1, 12, 362,   "Zwarte ooievaar")
GetSpeciesPlot(start_year,end_year, 1, 12, 285,   "Kuifaalscholver")
GetSpeciesPlot(start_year,end_year, 1, 12, 853,   "Zwarte Ibis")
GetSpeciesPlot(start_year,end_year, 1, 12, 4, 	"Woudaap")
GetSpeciesPlot(start_year,end_year, 1, 12, 5, 	"Kwak")
GetSpeciesPlot(start_year,end_year, 1, 12, 360, 	"Koereiger")
GetSpeciesPlot(start_year,end_year, 1, 12, 324, 	"Slangenarend")
GetSpeciesPlot(start_year,end_year, 1, 12, 334, 	"Steppekiekendief")
GetSpeciesPlot(start_year,end_year, 1, 12, 321, 	"Ruigpootbuizerd")
GetSpeciesPlot(start_year,end_year, 1, 12, 38, 	"Hop")
GetSpeciesPlot(start_year,end_year, 1, 12, 300, 	"Oehoe")
GetSpeciesPlot(start_year,end_year, 1, 12, 1386,  "Bijeneter")
GetSpeciesPlot(start_year,end_year, 1, 12, 39, 	"Draaihals")
GetSpeciesPlot(start_year,end_year, 1, 12, 290, 	"Middelste bonte specht")
GetSpeciesPlot(start_year,end_year, 1, 12, 316, 	"Roodpootvalk")
GetSpeciesPlot(start_year,end_year, 1, 12, 53, 	"Roodkopklauwier")
GetSpeciesPlot(start_year,end_year, 1, 12, 67, 	"Bonte kraai")
GetSpeciesPlot(start_year,end_year, 1, 12, 306, 	"Pestvogel")
GetSpeciesPlot(start_year,end_year, 1, 12, 1007,  "Roodstuitzwaluw")
GetSpeciesPlot(start_year,end_year, 1, 12, 262, 	"Hume's bladkoning")
GetSpeciesPlot(start_year,end_year, 1, 12, 227, 	"Bladkoning")
GetSpeciesPlot(start_year,end_year, 1, 12, 303, 	"Pallas' boszanger")
GetSpeciesPlot(start_year,end_year, 1, 12, 1503,  "Bruine boszanger")
GetSpeciesPlot(start_year,end_year, 1, 12, 765, 	"Siberische tjiftjaf")
GetSpeciesPlot(start_year,end_year, 1, 12, 252, 	"Grauwe fitis")
GetSpeciesPlot(start_year,end_year, 1, 12, 49, 	"Grote karekiet")
GetSpeciesPlot(start_year,end_year, 1, 12, 1129,  "Waterrietzanger")
GetSpeciesPlot(start_year,end_year, 1, 12, 1123,  "Struikrietzanger")
GetSpeciesPlot(start_year,end_year, 1, 12, 302, 	"Orpheusspotvogel")
GetSpeciesPlot(start_year,end_year, 1, 12, 1115,  "Krekelzanger")
GetSpeciesPlot(start_year,end_year, 1, 12, 1111,  "Graszanger")
GetSpeciesPlot(start_year,end_year, 1, 12, 371, 	"Sperwergrasmus")
GetSpeciesPlot(start_year,end_year, 1, 12, 80485, "Taigaboomkruiper ssp familiaris")
GetSpeciesPlot(start_year,end_year, 1, 12, 199294,"Roze spreeuw")
GetSpeciesPlot(start_year,end_year, 1, 12, 1182,  "Kleine vliegenvanger")
GetSpeciesPlot(start_year,end_year, 1, 12, 1561,  "Blauwsaart")
GetSpeciesPlot(start_year,end_year, 1, 12, 84884, "Waterspreeuw")
GetSpeciesPlot(start_year,end_year, 1, 12, 239,   "Citroenkwikstaart")
GetSpeciesPlot(start_year,end_year, 1, 12, 757,   "Grote pieper")
GetSpeciesPlot(start_year,end_year, 1, 12, 43,    "Duinpieper")
GetSpeciesPlot(start_year,end_year, 1, 12, 755,   "Roodkeelpieper")
GetSpeciesPlot(start_year,end_year, 1, 12, 315,   "Roodmus")
GetSpeciesPlot(start_year,end_year, 1, 12, 248,   "Europese kanarie")
GetSpeciesPlot(start_year,end_year, 1, 12, 57,    "Grauwe gors")
GetSpeciesPlot(start_year,end_year, 1, 12, 56,    "Ortolaan")
GetSpeciesPlot(start_year,end_year, 1, 12, 245,   "Dwerggors")
GetSpeciesPlot(start_year,end_year, 1, 12, 1529,  "Bosgors")
