name: Python Tests with Conda Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Clear pip cache
    - name: Clear pip cache
      run: |
        python -m pip cache purge

    # Clear conda cache
    - name: Clear conda cache
      run: |
        conda clean --all --yes

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        auto-activate-base: false

    - name: Run 'conda init' to setup Conda
      run: |
        conda init bash

    - name: Create Conda environment from environment.yml
      run: |
        conda env create -f environment.yml
        source ~/.bashrc  # To load the conda environment properly
        conda activate observadoscraper

    - name: Install dependencies
      run: |
        conda activate observadoscraper
        conda install --yes --file environment.yml

    - name: Run tests
      run: |
        conda activate observadoscraper
        pytest tests --maxfail=1 --disable-warnings -q