name: Python Tests with Conda Environment

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          channels: conda-forge
          mamba-version: "*"
          channel-priority: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: observadoscraper
          create-environment: true  # 👈 This line is critical!

      - name: Show Conda packages
        run: conda list

      - name: Run tests
        shell: bash -l {0}
        run: pytest tests --maxfail=1 --disable-warnings -q

